import type { AudiencePage } from "./types";

export const industryPages: Record<string, AudiencePage> = {
  "accounting-firms": {
    slug: "accounting-firms",
    title: "Incoming payment reconciliation for accounting firms",
    metaTitle: "Invoice Reconciliation for Accounting Firms | InvoiceReconcile",
    description: "Create a consistent client reconciliation procedure with isolated workspaces, prepared-by evidence, and reviewable exports.",
    eyebrow: "Accounting firms",
    intro: "Firms can standardize how staff investigate incoming customer payments without forcing every engagement into identical source files. The common layer is the evidence and sign-off method, not the client's chart of accounts.",
    painPoints: [{ title: "Many source systems", detail: "Client data arrives from different ledgers, banks, processors, and custom billing tools." }, { title: "Prepared-by evidence", detail: "Reviewers need more than a matched status to verify a preparer's conclusion." }, { title: "Engagement boundaries", detail: "Client identities, files, mappings, and transactions must remain isolated." }],
    workflow: [{ title: "Scope", detail: "Confirm client, bank account, period, currency, and source files." }, { title: "Prepare", detail: "Import and investigate suggestions inside the client workspace." }, { title: "Review", detail: "Require factual reasons and notes on material exceptions." }, { title: "Handoff", detail: "Export confirmed work and separately tie the client ledger." }],
    example: { label: "Reviewer-ready application", payment: "$8,750.00 wire", invoices: ["INV-8812  $5,250.00", "INV-8830  $3,500.00"], outcome: "Prepared, awaiting review", note: "The source file, reference evidence, preparer, and selected invoices remain connected for engagement review." },
    controls: ["Client workspaces with row-level isolation", "Firm roles enforced on the server", "Consistent match explanation fields", "Prepared and confirmed decision history", "Operational metrics without bank memo exposure", "Export control totals by engagement"],
    related: [{ href: "/solutions/accounting-firms", label: "Accounting firm solution" }, { href: "/payment-reconciliation-for-accounting-firms", label: "Firm reconciliation guide" }, { href: "/resources/invoice-reconciliation-checklist", label: "Reconciliation checklist" }],
  },
  bookkeepers: {
    slug: "bookkeepers",
    title: "A multi-client reconciliation routine for bookkeepers",
    metaTitle: "Invoice Reconciliation for Bookkeepers | InvoiceReconcile",
    description: "Move through client payment exceptions with isolated imports, visible source evidence, and a clear audit trail.",
    eyebrow: "Bookkeeping practices",
    intro: "Bookkeepers need speed without mixing one client's habits into another. A firm queue shows which workspaces need attention, then each client opens into its own import history, rules, exceptions, and exports.",
    painPoints: [{ title: "Monthly repetition", detail: "The same payer names and column mappings are rediscovered during every reconciliation cycle." }, { title: "Client interruptions", detail: "Missing remittance details create follow-up work that needs an owner and status." }, { title: "Context switching", detail: "A bookkeeper may touch ten ledgers in one day and needs the active workspace to remain obvious." }],
    workflow: [{ title: "Open client", detail: "Confirm the workspace and last completed reconciliation." }, { title: "Check mapping", detail: "Review the detected columns and correct uncertain mappings before processing." }, { title: "Clear queue", detail: "Review routine suggestions and add notes for follow-up." }, { title: "Deliver", detail: "Export confirmed, unmatched, and discrepancy reports." }],
    example: { label: "Payer name variation", payment: "$2,175.00 from HORIZON MGMT", invoices: ["Horizon Property Management", "INV-2195  $2,175.00"], outcome: "Name and amount support review", note: "The original payer text remains visible with the proposal and stays inside the client workspace." },
    controls: ["Active client shown in the workspace header", "Original payer evidence retained", "Detected column mappings with preview", "Review queue with explicit decisions", "Verified live data requests through support", "Audit log ready for client questions"],
    related: [{ href: "/solutions/bookkeepers", label: "Bookkeeper solution" }, { href: "/invoice-reconciliation-for-bookkeepers", label: "Multi-client guide" }, { href: "/tools/reconciliation-time-calculator", label: "Manual time calculator" }],
  },
  consulting: {
    slug: "consulting",
    title: "Reconcile consulting retainers, milestones, and invoice payments",
    metaTitle: "Invoice Reconciliation for Consulting Firms | InvoiceReconcile",
    description: "Match client ACH and wire payments to consulting invoices while keeping retainers, milestone partials, and deductions visible.",
    eyebrow: "Consulting firms",
    intro: "Consulting invoices often follow retainers, monthly service periods, or project milestones. Customer wires may reference a project or legal entity instead of the invoice number, which makes amount and payer evidence especially important.",
    painPoints: [{ title: "Entity names differ", detail: "The paying parent company may not match the project client's display name." }, { title: "Milestone partials", detail: "Customers may pay an approved portion while a disputed deliverable remains open." }, { title: "Retainer confusion", detail: "A receipt may relate to a retainer, an invoice, or both, depending on the contract and ledger treatment." }],
    workflow: [{ title: "Import open billing", detail: "Include invoice, project reference, customer ID, amount, and current balance." }, { title: "Import receipts", detail: "Preserve wire originator and memo details from the bank export." }, { title: "Review context", detail: "Use project references and payer identity evidence, not amount alone." }, { title: "Confirm treatment", detail: "Keep contract or accounting judgment outside the automatic match." }],
    example: { label: "Milestone underpayment", payment: "$18,000.00 wire", invoices: ["MS-04  $20,000.00"], outcome: "Review $2,000.00 shortfall", note: "The difference could be a disputed milestone, withholding, or error. The reconciliation keeps it visible for project and finance review." },
    controls: ["Project and PO references retained", "Partial applications preserve the open balance", "Parent and subsidiary payer evidence remains inspectable", "Notes support project-team follow-up", "No automatic write-off of shortfalls", "Confirmed export separates applied and unapplied amounts"],
    related: [{ href: "/partial-payment-reconciliation", label: "Partial payment workflow" }, { href: "/bank-deposit-to-invoice-matching", label: "Wire and ACH matching" }, { href: "/resources/how-to-handle-partial-invoice-payments", label: "Handle partial payments" }],
  },
  "marketing-agencies": {
    slug: "marketing-agencies",
    title: "Match agency retainers and campaign invoices to incoming payments",
    metaTitle: "Invoice Reconciliation for Marketing Agencies | InvoiceReconcile",
    description: "Reconcile retainers, project invoices, and pass-through billing against customer payments and processor deposits.",
    eyebrow: "Marketing agencies",
    intro: "Agencies often bill monthly retainers alongside projects, media, and reimbursable costs. A client may combine several invoices in one transfer or subtract a disputed pass-through amount, creating an exception that a simple lookup cannot explain.",
    painPoints: [{ title: "Several invoice types", detail: "Retainers, projects, media, and reimbursables may be paid together but tracked separately." }, { title: "Client brand versus legal payer", detail: "The bank description may use a parent entity or treasury provider rather than the familiar brand." }, { title: "Disputed pass-through costs", detail: "A short payment may need account-manager context before finance can apply it." }],
    workflow: [{ title: "Preserve invoice context", detail: "Import campaign, PO, and client references where available." }, { title: "Find combinations", detail: "Narrow open balances to the payer before searching exact totals." }, { title: "Route shortfalls", detail: "Mark possible deductions for review instead of assuming a fee." }, { title: "Close the loop", detail: "Add a note and export the confirmed application for the ledger." }],
    example: { label: "Retainer plus project", payment: "$11,500.00 ACH", invoices: ["August retainer  $7,500.00", "Campaign launch  $4,000.00"], outcome: "2 invoices match total", note: "Client identity and billing references support the combination before finance confirms it." },
    controls: ["One-to-many applications", "Brand and legal payer names remain visible", "Possible deduction status for short payments", "Notes for account-manager follow-up", "Invoice references retained from the source", "Confirmed-only exports"],
    related: [{ href: "/combined-payment-invoice-matching", label: "Combined payment matching" }, { href: "/partial-payment-reconciliation", label: "Partial payment review" }, { href: "/tools/lump-sum-invoice-matcher", label: "Try the lump-sum matcher" }],
  },
  "home-services": {
    slug: "home-services",
    title: "Reconcile deposits and job invoices for home service businesses",
    metaTitle: "Invoice Reconciliation for Home Services | InvoiceReconcile",
    description: "Match checks, ACH deposits, and processor payments to job invoices while handling customer names, deposits, and partial collections.",
    eyebrow: "Home services",
    intro: "Home service businesses can receive payments from homeowners, property managers, insurers, and general contractors. The payer name may not match the job customer, and one payment may cover several locations or work orders.",
    painPoints: [{ title: "Payer is not the customer", detail: "A property manager or insurer may pay an invoice issued under a homeowner or property name." }, { title: "Job deposits", detail: "Upfront and progress payments create multiple receipts against one job invoice." }, { title: "Batch processor deposits", detail: "Card settlements may combine jobs and subtract fees before the bank deposit appears." }],
    workflow: [{ title: "Import job invoices", detail: "Include job, property, customer, invoice, and outstanding balance references." }, { title: "Import posted receipts", detail: "Keep payer, check, ACH, and processor identifiers." }, { title: "Review relationships", detail: "Confirm payer identity and split batch deposits carefully." }, { title: "Preserve balance", detail: "Leave progress amounts open until later payments arrive." }],
    example: { label: "Property manager pays two jobs", payment: "$3,600.00 ACH", invoices: ["Job 4811  $1,400.00", "Job 4850  $2,200.00"], outcome: "2 work orders match total", note: "The payer name, work-order references, and exact total support the application across two customer invoices." },
    controls: ["Job and property references preserved", "Several payments can settle one invoice", "Payer evidence stays inside the workspace", "Processor fees require confirmation", "Duplicate checks across recurring exports", "Unmatched receipts remain visible"],
    related: [{ href: "/combined-payment-invoice-matching", label: "Combined payments" }, { href: "/partial-payment-reconciliation", label: "Progress payments" }, { href: "/resources/why-bank-deposits-and-invoice-totals-do-not-always-match", label: "Why deposits differ" }],
  },
  "wholesale-distribution": {
    slug: "wholesale-distribution",
    title: "Reconcile wholesale remittances across many open invoices",
    metaTitle: "Payment Reconciliation for Wholesale Distribution | InvoiceReconcile",
    description: "Match high-line-count customer remittances, short pays, and combined ACH payments to wholesale invoices.",
    eyebrow: "Wholesale distribution",
    intro: "Wholesale customers frequently pay many invoices in one remittance and may deduct shortages, returns, freight, or allowances. An exact total search helps only after the candidate account and deduction evidence have been narrowed.",
    painPoints: [{ title: "High invoice counts", detail: "A single customer account may have dozens of eligible balances within one payment window." }, { title: "Short pays and deductions", detail: "The payment may reference claims, returns, or allowances that require separate validation." }, { title: "Remittance arrives separately", detail: "The bank receipt and the customer's invoice detail may reach different people or systems." }],
    workflow: [{ title: "Narrow the account", detail: "Use payer, customer ID, currency, and remittance references before combination search." }, { title: "Match referenced lines", detail: "Apply exact invoice references first and preserve unresolved differences." }, { title: "Classify exceptions", detail: "Separate possible deductions from unidentified cash and duplicate records." }, { title: "Confirm with evidence", detail: "Attach reviewer notes and maintain the remaining customer balance." }],
    example: { label: "Short-paid remittance", payment: "$24,650.00 ACH", invoices: ["5 referenced invoices  $25,000.00"], outcome: "Review $350.00 deduction", note: "The application can identify the referenced invoices without deciding whether the deduction is valid." },
    controls: ["Bounded subset search after customer narrowing", "Reference extraction from bank and remittance text", "Possible deduction tracked separately", "One payment to many invoice links", "Unapplied and remaining amounts shown", "Decision history for customer disputes"],
    related: [{ href: "/cash-application-automation", label: "Cash application automation" }, { href: "/combined-payment-invoice-matching", label: "Combined invoice matching" }, { href: "/resources/how-to-reconcile-processing-fees-against-invoices", label: "Fee and deduction workflow" }],
  },
  "b2b-services": {
    slug: "b2b-services",
    title: "Incoming payment reconciliation for B2B service companies",
    metaTitle: "Payment Reconciliation for B2B Services | InvoiceReconcile",
    description: "Connect external ACH and wire payments with service invoices, retainers, and multi-entity customer accounts.",
    eyebrow: "B2B services",
    intro: "B2B service companies often invoice one operating contact and receive money from a parent company, payment portal, or outsourced treasury team. References can be strong, missing, or formatted differently across every channel.",
    painPoints: [{ title: "Complex customer identity", detail: "Contract name, invoice customer, and bank originator may represent different entities in the same group." }, { title: "External ACH and wires", detail: "Payments arrive outside the billing platform with truncated bank descriptions." }, { title: "Mixed billing periods", detail: "Customers may combine current invoices, overdue balances, and credits in one transfer." }],
    workflow: [{ title: "Map customer identity", detail: "Use explicit, editable aliases between known payers and invoiced entities." }, { title: "Extract references", detail: "Normalize invoice numbers while preserving the full source memo." }, { title: "Investigate totals", detail: "Find exact, grouped, partial, and overpayment relationships." }, { title: "Confirm and follow up", detail: "Export confirmed work and assign unresolved receipts." }],
    example: { label: "Parent entity wire", payment: "$6,900.00 from NORTH GROUP", invoices: ["North Systems  $4,100.00", "North Advisory  $2,800.00"], outcome: "Review cross-entity allocation", note: "The amount is exact, but entity policy and customer mapping need human confirmation before application." },
    controls: ["Editable payer-to-customer mappings", "Original bank descriptions retained", "Currency conflicts block automatic reconciliation", "Grouped and partial relationships modeled explicitly", "Notes capture collection follow-up", "No silent cross-customer applications"],
    related: [{ href: "/bank-deposit-to-invoice-matching", label: "Bank deposit matching" }, { href: "/invoice-payment-matching", label: "Invoice payment relationships" }, { href: "/tools/invoice-reference-cleaner", label: "Clean invoice references" }],
  },
};

export const industrySlugs = Object.keys(industryPages);
