import type { ResourceArticle } from "./types";

export const resources: ResourceArticle[] = [
  {
    slug: "how-to-reconcile-customer-payments-to-invoices",
    title: "How to reconcile customer payments to invoices",
    description: "A practical source-to-ledger procedure for matching incoming customer payments, reviewing discrepancies, and preserving evidence.",
    category: "How-to",
    readingMinutes: 8,
    updated: "2026-08-23",
    intro: "Customer payment reconciliation connects cash received with the invoices and balances it is intended to settle. The process should explain every applied amount, preserve anything unresolved, and leave enough evidence for another reviewer to reproduce the decision.",
    sections: [
      { heading: "1. Define the period and source records", paragraphs: ["Choose the posted payment date range and confirm the bank accounts, processors, currencies, and workspaces in scope. Export open invoices as of a consistent point in time. Keep the source files unchanged and record when each export was created.", "At minimum, invoice data needs a stable identifier, customer, original amount, current outstanding balance, invoice date, and currency. Payment data needs a source transaction ID where available, posted date, amount, payer or description, reference, and currency."], bullets: ["Open invoice export", "Posted bank or processor payments", "Credit and prior-application information", "Reconciliation period and reviewer"] },
      { heading: "2. Validate before matching", paragraphs: ["Check row counts, control totals, blank required fields, duplicate transaction IDs, duplicate invoices, date formats, and currency parsing. Preview mapped columns before importing. Do not silently drop rows that fail validation.", "Normalize copies of names and references for comparison while retaining the original values. Currency values should use fixed decimal units, such as cents, rather than binary floating point equality."] },
      { heading: "3. Match strong evidence first", paragraphs: ["Start with exact amount and currency, then add invoice references, payer similarity, customer identifiers, and a reasonable date window. A payment with an invoice number in the memo and an exact balance is stronger than an amount-only match.", "Remove confirmed exact items from the active queue. This reduces the candidate pool for combined and partial cases and gives the reviewer a smaller set of meaningful exceptions."] },
      { heading: "4. Work the exceptions deliberately", paragraphs: ["For one payment covering several invoices, narrow candidates by customer and then search plausible combinations. For partial payments, store the applied and remaining balances. For fees and deductions, show the difference and require evidence before classification.", "If multiple candidates remain plausible, leave the item in review. If no responsible candidate exists, keep the payment unmatched and state what information is missing."], bullets: ["Combined invoice payments", "Several payments against one invoice", "Partials and overpayments", "Fees, deductions, duplicates, and missing references"] },
      { heading: "5. Confirm, export, and tie totals", paragraphs: ["Record who confirmed each application, when it happened, the source transaction, selected invoices, prior state, resulting state, and any note. Export confirmed applications separately from unmatched payments and discrepancies.", "Finally, verify the exported result in the accounting system and complete any broader accounts receivable or bank reconciliation controls required by the business. Matching assistance does not replace accounting review."] },
    ],
    example: { label: "Exact reference match", payment: "$1,250.00, memo INV10487", invoices: ["INV10487  $1,250.00 open"], outcome: "Exact amount and reference", note: "Customer identity, currency, and duplicate status should still be checked before confirmation." },
    takeaways: ["Preserve source files and original field values.", "Use deterministic evidence before more flexible similarity signals.", "Keep applied, remaining, and unapplied amounts separate.", "Require a human decision for ambiguity and discrepancies.", "Tie confirmed exports back to the accounting ledger."],
    related: ["invoice-reconciliation-checklist", "accounts-receivable-reconciliation-explained", "why-bank-deposits-and-invoice-totals-do-not-always-match"],
  },
  {
    slug: "how-to-match-one-payment-to-multiple-invoices",
    title: "How to match one payment to multiple invoices",
    description: "Find and verify the invoice combination behind a lump-sum customer payment without relying on amount coincidence alone.",
    category: "How-to",
    readingMinutes: 7,
    updated: "2026-08-23",
    intro: "A single ACH, wire, or check can settle several invoices. The mathematical problem is finding balances that add to the payment. The reconciliation problem is proving that the selected balances belong to the payer and period.",
    sections: [
      { heading: "Collect the strongest identity evidence", paragraphs: ["Start with the payer name, customer ID, bank originator, remittance email, check number, and any invoice references. Map known parent-company or treasury names through explicit aliases that a reviewer can inspect.", "Do not search every invoice across every customer solely because the totals might agree. Coincidental combinations become common as the open invoice list grows."] },
      { heading: "Narrow the candidate pool", paragraphs: ["Keep only open invoices with compatible currency, a plausible customer relationship, and dates consistent with the payment. Prefer directly referenced invoices. Apply a documented limit to candidate count and combination size.", "Narrowing improves both speed and quality. It also makes the final explanation easier to review because every candidate passed the same initial scope rules."], bullets: ["Same customer or approved payer alias", "Same currency", "Open balance at the payment date", "Within the configured date window", "Referenced in remittance or bank text"] },
      { heading: "Search combinations using integer amounts", paragraphs: ["Convert amounts to cents and search subsets that equal the payment. A bounded depth-first search or dynamic approach can work for a small, narrowed list. Stop or warn when limits are reached rather than allowing a large import to freeze the interface.", "Return every plausible exact combination within the limit. If two sets produce the same total, the result is ambiguous until other evidence separates them."] },
      { heading: "Verify each application line", paragraphs: ["Show invoice number, date, customer, open balance, and proposed applied amount for every selected invoice. The payment total should equal the sum of applications plus any visible unapplied amount.", "When one invoice is only partly covered, preserve its remaining balance. A combined payment can contain full and partial applications in the same decision."] },
      { heading: "Record the one-to-many relationship", paragraphs: ["Create separate links between the payment and every invoice rather than storing a comma-separated invoice list. The audit record should include the matching method, reasons, reviewer, source file, and decision.", "After confirmation, verify the destination accounting ledger and keep any remittance evidence according to the organization's retention policy."] },
    ],
    example: { label: "Three-invoice ACH", payment: "$4,725.00", invoices: ["INV-2108  $1,500.00", "INV-2141  $1,225.00", "INV-2190  $2,000.00"], outcome: "Exact combined total", note: "The combination is strong when the payer, currency, and remittance references also agree." },
    takeaways: ["Narrow by identity and currency before searching totals.", "Use cents and bounded combination limits.", "Return ambiguity when several combinations work.", "Model each payment-to-invoice link separately.", "Confirm the final allocation before ledger posting."],
    related: ["what-to-do-when-customer-pays-multiple-invoices-in-one-ach", "invoice-reconciliation-checklist", "how-to-handle-partial-invoice-payments"],
  },
  {
    slug: "what-to-do-when-customer-pays-multiple-invoices-in-one-ach",
    title: "What to do when a customer pays multiple invoices in one ACH",
    description: "Use ACH originator details, remittance references, and open balances to document a multi-invoice customer payment.",
    category: "How-to",
    readingMinutes: 6,
    updated: "2026-08-23",
    intro: "One ACH can contain payment for several invoice balances. Before searching combinations, confirm that the deposit is a customer payment rather than a processor batch, transfer, loan, or another type of bank activity.",
    sections: [
      { heading: "Read the complete ACH detail", paragraphs: ["Capture the posted date, amount, originator name, company ID, trace or transaction ID, entry description, and addenda text that your bank provides. Bank interfaces may truncate the visible row, so use the export or detail view when possible.", "Preserve that source text. A cleaned name helps matching, but the raw company ID or trace value may be the best evidence later."] },
      { heading: "Locate remittance information", paragraphs: ["Search the ACH addenda, customer email, remittance portal, or shared AR inbox for invoice references. If remittance arrives separately, connect it to the payment through a stable transaction or customer reference.", "Do not rely on an emailed spreadsheet without checking that its total equals the posted ACH and that the invoice balances were open for the stated amount."] },
      { heading: "Compare referenced invoices first", paragraphs: ["Load the referenced invoices and total their current outstanding balances. If the sum equals the ACH, verify customer, currency, date, and duplicates before confirmation.", "If the total differs, identify whether the remittance includes a partial, credit, deduction, or invoice that has already been paid. Keep the difference explicit while investigating."] },
      { heading: "Search a narrowed open list when references are missing", paragraphs: ["Use the payer-to-customer mapping and compatible currency to build a small set of open invoices. Search combinations within reasonable count and size limits. A mathematical total without identity support stays in review.", "Contact the customer for remittance advice if several plausible combinations remain. Recording the follow-up is better than forcing an allocation that will need to be reversed."] },
      { heading: "Confirm and document", paragraphs: ["Apply the ACH to each confirmed invoice, preserve any partial or unapplied amount, and record the reviewer and evidence. Verify the accounting system after posting or import.", "If the payer name is recurring, save an explicit workspace-level alias. Keep it editable so a later entity change does not become opaque matching behavior."] },
    ],
    example: { label: "ACH with no invoice list", payment: "$6,300.00 from ACME HOLDINGS", invoices: ["Acme Services  $2,800.00", "Acme Services  $3,500.00"], outcome: "Plausible combined match", note: "The approved payer alias and exact total support the proposal, but remittance evidence provides the best confirmation." },
    takeaways: ["Capture the full ACH detail and stable identifiers.", "Connect separate remittance records to the payment.", "Investigate any difference from the remittance total.", "Ask for clarification when several combinations remain.", "Save payer aliases transparently and per workspace."],
    related: ["how-to-match-one-payment-to-multiple-invoices", "why-bank-deposits-and-invoice-totals-do-not-always-match", "how-to-reconcile-customer-payments-to-invoices"],
  },
  {
    slug: "how-to-handle-partial-invoice-payments",
    title: "How to handle partial invoice payments",
    description: "Document partial customer payments, preserve the open balance, and distinguish installments from deductions or errors.",
    category: "How-to",
    readingMinutes: 7,
    updated: "2026-08-23",
    intro: "A payment below the outstanding invoice balance can be valid, but the amount alone does not explain why it is short. The workflow needs to preserve the application and remaining balance while the reviewer identifies the business reason.",
    sections: [
      { heading: "Confirm that the payment belongs to the invoice", paragraphs: ["Use invoice reference, customer identity, currency, date, and remittance details. An amount that happens to be half of an invoice is not enough when the customer has several open balances.", "Check whether another payment or credit was already applied. Stale open-invoice exports can make a full settlement appear partial."] },
      { heading: "Classify the situation without guessing", paragraphs: ["Common explanations include a planned installment, contract deposit, disputed line item, withholding, early-payment discount, processor fee, or simple payment error. Request supporting evidence before recording a deduction or write-off.", "Matching software should allow a reviewer to mark a partial application without claiming an accounting reason it cannot prove."] },
      { heading: "Calculate the application", paragraphs: ["The applied amount cannot exceed the payment or current invoice balance. Subtract the confirmed application from both to get the invoice balance remaining and any payment amount unapplied.", "Example: a $2,500 receipt against a $5,000 open invoice leaves $2,500 due and no unapplied cash when the full receipt is assigned."], bullets: ["Applied = amount assigned to this invoice", "Invoice remaining = open balance minus applied", "Payment unapplied = payment amount minus all applications", "Cumulative applied = sum of confirmed source payments"] },
      { heading: "Keep later payments connected", paragraphs: ["Each later receipt should remain a separate source transaction linked to the same invoice. The invoice history can then show every application, reversal, and remaining balance.", "Use source transaction IDs and import lineage to detect when a recurring export contains a payment already processed in an earlier period."] },
      { heading: "Follow up and close", paragraphs: ["Assign unresolved shortfalls to a person and record the next action. Once the customer explains the difference, update the note and use the accounting system's approved treatment for deductions, credits, or write-offs.", "Reconciliation assistance is not accounting or tax advice. Confirm the policy with the responsible professional when judgment is required."] },
    ],
    example: { label: "Planned installment", payment: "$2,500.00", invoices: ["INV-5007  $5,000.00 open"], outcome: "$2,500.00 remains due", note: "The invoice stays open and the source payment remains traceable after application." },
    takeaways: ["Verify identity and current balance before applying.", "Do not infer the reason from the amount alone.", "Separate invoice remaining and payment unapplied amounts.", "Link every installment to its source transaction.", "Assign unresolved shortfalls for follow-up."],
    related: ["how-to-reconcile-processing-fees-against-invoices", "invoice-reconciliation-checklist", "how-to-reconcile-customer-payments-to-invoices"],
  },
  {
    slug: "how-to-reconcile-processing-fees-against-invoices",
    title: "How to reconcile processing fees against invoices",
    description: "Explain fee-net deposits without silently reducing customer invoice balances or assuming every difference is a processor fee.",
    category: "How-to",
    readingMinutes: 7,
    updated: "2026-08-23",
    intro: "A processor may deposit the customer payment net of fees, batch several transactions, or withdraw fees separately. The bank deposit and invoice total can therefore differ even when the customer paid in full.",
    sections: [
      { heading: "Identify the settlement model", paragraphs: ["Read the processor settlement report and fee schedule. Determine whether fees are netted from each deposit, netted from a batch, or withdrawn in a separate transaction. Also confirm the settlement timing and reserve behavior.", "Do not assume a short bank deposit is a fee. Customer deductions, refunds, chargebacks, withholding, and data errors can produce similar differences."] },
      { heading: "Reconcile three layers", paragraphs: ["Compare the customer payment or payments, processor settlement, and bank deposit. The customer application may use the gross amount, while the bank receives the net amount and the fee is handled separately under the business's accounting policy.", "For a batch, total all included gross payments, subtract documented fees and other adjustments, and compare the result with the posted deposit."], bullets: ["Gross customer receipts", "Refunds, disputes, reserves, or adjustments", "Documented processor fees", "Net bank deposit"] },
      { heading: "Require evidence for the difference", paragraphs: ["Attach or reference the settlement identifier and report row that explains the fee. A consistent historical percentage can be a useful signal, but it is not proof for a new transaction.", "If the report does not explain the difference, keep the item as a review exception and contact the processor or investigate the source batch."] },
      { heading: "Preserve invoice and bank relationships", paragraphs: ["Link the gross customer receipt to the invoice application and the settlement to the bank deposit through source identifiers. This avoids changing the customer payment to match the net bank amount.", "The exact ledger entries depend on the accounting system and company policy. A reviewer should verify the posting rather than relying solely on the matching tool."] },
      { heading: "Watch for duplicates and timing", paragraphs: ["Processor exports and bank feeds may show different representations of the same money movement. Source lineage and transaction IDs prevent double counting.", "Settlement dates may lag customer payment dates and cross a month end. Document the cutoff procedure and reconcile timing items consistently."] },
    ],
    example: { label: "Net processor settlement", payment: "$4,850.00 bank deposit", invoices: ["Gross customer payment  $5,000.00", "Processor report fee  $150.00"], outcome: "Net amount explained", note: "The processor report supports the difference. A reviewer still confirms the invoice application and accounting treatment." },
    takeaways: ["Learn whether fees are netted or withdrawn separately.", "Tie gross receipts, settlement, fees, and net deposit.", "Use settlement evidence, not a guessed percentage.", "Keep the gross invoice application distinct from bank cash.", "Document timing and source lineage."],
    related: ["why-bank-deposits-and-invoice-totals-do-not-always-match", "how-to-handle-partial-invoice-payments", "cash-application-explained-for-small-businesses"],
  },
  {
    slug: "invoice-reconciliation-checklist",
    title: "Invoice reconciliation checklist",
    description: "A repeatable checklist for validating source files, reviewing match evidence, resolving exceptions, and verifying exports.",
    category: "Checklist",
    readingMinutes: 6,
    updated: "2026-08-23",
    intro: "Use this checklist as a starting control, then adapt ownership, materiality, retention, and sign-off to the business. It focuses on incoming customer payments and open receivables, not supplier invoices.",
    sections: [
      { heading: "Scope and source", paragraphs: ["Confirm the organization, workspace, bank or processor account, currency, date range, and current open-invoice cutoff. Record who prepared each source export and when.", "Store source files privately with a documented retention period. Do not email sensitive exports broadly or upload them through an unauthenticated form."], bullets: ["Correct client and workspace", "Posted payment period", "Open invoice as-of date", "Source accounts and currencies", "Named preparer and reviewer"] },
      { heading: "Import validation", paragraphs: ["Preview column mappings and totals before processing. Investigate blank identifiers, invalid dates, malformed amounts, duplicate rows, repeated files, multiple worksheets, and currency conflicts.", "Keep rejected rows visible with a specific recovery instruction. Never let an import silently discard records."] },
      { heading: "Match review", paragraphs: ["Confirm that every proposed match shows payment, invoice, amount, currency, date, payer, references, method, and reasons. Treat confidence as a routing label, not a guarantee.", "Bulk approve only clearly identified high-confidence items under an explicit policy. Uncertain matches should never be approved merely to reduce the queue."], bullets: ["Exact amount and reference evidence", "Combined invoice allocation", "Partial and remaining balances", "Overpayment and unapplied cash", "Ambiguity, duplicates, and currency mismatch"] },
      { heading: "Exception resolution", paragraphs: ["Assign an owner and next action to every unresolved item. Preserve evidence for fee differences, deductions, customer credits, and write-offs. Contact the customer for remittance when combinations remain ambiguous.", "Record corrections as new audit actions rather than editing history until the prior decision disappears."] },
      { heading: "Export and close", paragraphs: ["Export confirmed applications, unmatched payments, discrepancies, and the audit record as required. Compare control totals before and after the export and verify the destination accounting ledger.", "Complete broader AR subledger, general ledger, bank, and cutoff reconciliations separately. Payment matching is one part of the close process."] },
    ],
    takeaways: ["Scope the right client, period, and currencies.", "Validate all rows before matching.", "Review visible evidence, not opaque confidence.", "Keep unresolved items owned and explicit.", "Tie exports and verify the accounting ledger."],
    related: ["how-to-reconcile-customer-payments-to-invoices", "accounts-receivable-reconciliation-explained", "how-to-reconcile-invoices-in-excel"],
  },
  {
    slug: "accounts-receivable-reconciliation-explained",
    title: "Accounts receivable reconciliation explained",
    description: "Understand AR reconciliation, customer payment application, the control account, aging, unapplied cash, and common exceptions.",
    category: "Explainer",
    readingMinutes: 8,
    updated: "2026-08-23",
    intro: "Accounts receivable reconciliation supports confidence that customer balances are complete, accurate, and connected to the accounting records. Incoming payment matching is an important operational step, but it is not the whole control.",
    sections: [
      { heading: "What sits inside accounts receivable", paragraphs: ["The AR subledger contains customer invoices, receipts, credits, adjustments, and remaining balances. The general ledger usually contains a receivables control account. A period-end process may need to tie the subledger total to that control account and investigate differences.", "Aging reports organize open balances by age, while payment application explains which receipts reduced which invoices. Unapplied cash and customer credits need separate review."] },
      { heading: "Payment matching versus AR reconciliation", paragraphs: ["Payment matching compares incoming receipts with open invoice balances and creates proposed applications. AR reconciliation also considers completeness, posting, cutoff, credit memos, write-offs, foreign currency, and the relationship between subsidiary and general ledger records.", "A matching tool can prepare evidence and exceptions, but accounting judgment and final ledger review remain with the business."] },
      { heading: "A practical period-end sequence", paragraphs: ["Confirm the period and refresh source reports. Match posted customer receipts, review unapplied cash and negative customer balances, investigate old or unusual items, and compare the AR subledger to the control account.", "Document reconciling items with owners and expected resolution dates. Verify subsequent activity where it supports the cutoff conclusion."], bullets: ["Refresh the customer aging and open invoices", "Apply or explain posted receipts", "Review credits, unapplied cash, and negative balances", "Tie the subledger to the control account", "Document cutoff and reconciling items"] },
      { heading: "Common causes of differences", paragraphs: ["Timing differences, duplicate imports, receipts posted to the wrong customer, credits not applied, write-offs, manual journal entries to the control account, foreign currency changes, and stale exports can all create disagreement.", "Work from source identifiers and totals. Changing individual records until the reports agree can hide the cause and weaken the audit trail."] },
      { heading: "Keep AR and AP terminology separate", paragraphs: ["Accounts receivable concerns amounts customers owe the business. Accounts payable concerns amounts the business owes vendors. Incoming customer payment matching is an AR workflow. Supplier invoice matching is an AP workflow.", "Using the correct terms helps teams choose the right source records, ownership, and controls." ] },
    ],
    example: { label: "Unapplied overpayment", payment: "$5,250.00", invoices: ["INV-3314  $5,000.00"], outcome: "$250.00 customer credit or unapplied", note: "A reviewer determines the correct ledger treatment under the company's policy." },
    takeaways: ["Payment application is one part of AR reconciliation.", "Tie the customer subledger to the general ledger control account.", "Review unapplied cash, credits, and negative balances.", "Document reconciling items instead of forcing agreement.", "Do not confuse AR with accounts payable."],
    related: ["how-to-reconcile-customer-payments-to-invoices", "invoice-reconciliation-checklist", "cash-application-explained-for-small-businesses"],
  },
  {
    slug: "cash-application-explained-for-small-businesses",
    title: "Cash application explained for small businesses",
    description: "A plain-language guide to applying customer receipts, handling exceptions, and keeping the accounting system in control.",
    category: "Explainer",
    readingMinutes: 7,
    updated: "2026-08-23",
    intro: "Cash application means assigning incoming customer money to the invoices or account balances it is intended to settle. Small businesses often do this inside the accounting system, in a spreadsheet, or through a combination of bank and billing exports.",
    sections: [
      { heading: "The basic information flow", paragraphs: ["The invoice system says what customers owe. The bank or payment processor says what money arrived. Remittance advice says what the customer intended to pay. Cash application brings these records together and creates a reviewed allocation.", "When the customer pays through a tightly linked payment channel, much of the information may already travel together. External ACH, wires, checks, and processor deposits often require more investigation."] },
      { heading: "A clean payment is straightforward", paragraphs: ["Suppose invoice INV-10487 has $1,250 outstanding and an ACH for $1,250 includes INV10487 in its memo. After checking customer, currency, date, and duplicate status, the evidence supports a strong one-to-one application.", "The confirmation should still record the source transaction and reviewer. Strong automation shortens the review, but it does not erase accountability."] },
      { heading: "The difficult cases", paragraphs: ["One receipt can pay several invoices. Several receipts can settle one invoice. A customer can pay partially, overpay, deduct an amount, omit a reference, or use a different legal entity name. A processor can combine receipts and subtract fees.", "These are normal operating exceptions, not reasons to hide a difference. A useful queue gives each case a factual explanation and a set of deliberate actions."], bullets: ["Exact and reference matches", "Combined and partial applications", "Fees, deductions, and overpayments", "Payer name variations and missing references", "Duplicates and unresolved receipts"] },
      { heading: "A small-team operating procedure", paragraphs: ["Import posted receipts and current open balances on a set cadence. Confirm strong matches, assign exception follow-up, export only confirmed applications, and verify the accounting system. Keep unresolved payments visible between cycles.", "Store payer aliases and mapping rules transparently. If the only person who knows that HORIZON MGMT means Horizon Property Management is out of office, the process should still be understandable."] },
      { heading: "What automation should and should not do", paragraphs: ["Automation can parse files, normalize references, detect duplicates, find combinations, rank candidates, and organize exceptions. It should not silently decide accounting treatment for a discrepancy or change the books without deliberate confirmation.", "Measure whether reviewers reach a correct result faster, not merely whether the software labels more transactions as matched."] },
    ],
    example: { label: "Simple cash application", payment: "$1,250.00 ACH", invoices: ["INV-10487  $1,250.00"], outcome: "Invoice balance becomes $0 after confirmation", note: "The accounting system remains the final ledger. The match is verified before posting or export." },
    takeaways: ["Cash application connects receipts with customer obligations.", "Remittance is often the best evidence for grouped payments.", "Keep difficult cases in a visible exception queue.", "Make aliases and rules inspectable.", "Require deliberate confirmation before ledger changes."],
    related: ["how-to-reconcile-customer-payments-to-invoices", "accounts-receivable-reconciliation-explained", "why-bank-deposits-and-invoice-totals-do-not-always-match"],
  },
  {
    slug: "how-to-reconcile-invoices-in-excel",
    title: "How to reconcile invoices in Excel",
    description: "Set up source tables, normalized columns, applications, exceptions, formulas, and controls for incoming payment reconciliation in Excel.",
    category: "How-to",
    readingMinutes: 9,
    updated: "2026-08-23",
    intro: "Excel can support a reliable low-volume reconciliation when the workbook separates source records from calculations and applications. The objective is to make changes visible and totals reproducible, not to create the cleverest formula.",
    sections: [
      { heading: "Create four structured tables", paragraphs: ["Use separate Excel tables for Invoices, Payments, Applications, and Exceptions. Do not put all four concepts into one wide sheet. Assign stable identifiers and preserve the original exported values.", "The Applications table should contain PaymentID, InvoiceID, AppliedAmount, Status, Reviewer, and ReviewedAt. Multiple rows naturally support one payment to several invoices and several payments to one invoice."], bullets: ["Invoices: invoice ID, customer, dates, original and open amount, currency", "Payments: payment ID, date, amount, payer, memo, currency", "Applications: payment ID, invoice ID, applied amount, decision", "Exceptions: type, owner, next action, note"] },
      { heading: "Add normalized helper columns", paragraphs: ["Create normalized copies of customer names and references. Typical cleaning includes trimming whitespace, standardizing case, and removing clearly irrelevant punctuation. Keep the original text beside the helper value.", "Convert currency values to fixed decimal numbers and dates to actual Excel dates. Flag rows that remain text or produce an error instead of wrapping every formula in IFERROR and hiding the problem."] },
      { heading: "Match one-to-one items", paragraphs: ["Use XLOOKUP, FILTER, or Power Query to identify candidate invoices with the same amount and currency. Add customer and reference checks so a common amount does not create a false match.", "Return a review status when several invoices fit. A lookup that selects the first result is not a reliable reconciliation method."] },
      { heading: "Handle combined and partial payments", paragraphs: ["For a small invoice list, test combinations manually or use Solver with binary selection cells. Always narrow the list to one customer and currency first. For partials, create an application row for the amount paid and calculate the remaining invoice balance from confirmed applications.", "Avoid circular formulas that use a result to define its own source range. Recalculate control totals after adding rows or refreshing Power Query."] },
      { heading: "Add workbook controls", paragraphs: ["Protect formula columns, use data validation for statuses, add duplicate ID checks, and display control totals for imported, applied, unapplied, and outstanding amounts. Archive a reviewed copy for each period and document the workbook owner.", "When source formats, volume, reviewers, or exception complexity grow, compare the effort of maintaining these controls with a dedicated workflow."] },
    ],
    example: { label: "Applications table", payment: "PAY-2408  $4,725.00", invoices: ["INV-2108  $1,500.00", "INV-2141  $1,225.00", "INV-2190  $2,000.00"], outcome: "3 application rows total $4,725.00", note: "Separate rows preserve the relationship and make control totals easier to calculate." },
    takeaways: ["Separate source, application, and exception tables.", "Keep original values beside normalized helpers.", "Do not accept the first amount lookup when several records fit.", "Use one row per payment-to-invoice application.", "Protect formulas and archive reviewed versions."],
    related: ["invoice-reconciliation-checklist", "how-to-match-one-payment-to-multiple-invoices", "how-to-reconcile-customer-payments-to-invoices"],
  },
  {
    slug: "why-bank-deposits-and-invoice-totals-do-not-always-match",
    title: "Why bank deposits and invoice totals do not always match",
    description: "Understand grouped deposits, fees, partials, deductions, timing, credits, currency, and data issues before forcing a match.",
    category: "Explainer",
    readingMinutes: 7,
    updated: "2026-08-23",
    intro: "A bank deposit is evidence of cash movement. An invoice balance is evidence of a customer obligation. They often relate, but timing and processing steps can change how the two amounts appear.",
    sections: [
      { heading: "Several invoices may be paid together", paragraphs: ["A customer can include multiple invoice balances in one ACH, wire, or check. The deposit equals a combination rather than one invoice. Use remittance references and customer identity to narrow the invoices before searching totals.", "When several mathematical combinations work, request additional evidence instead of selecting the first result."] },
      { heading: "Several payments may be deposited together", paragraphs: ["A processor or bank deposit can batch receipts from different customers. The bank shows one net amount while the settlement report lists the underlying payments. Reconcile the batch to the report before trying to link the deposit directly to invoices.", "Source identifiers should connect invoice applications, customer receipts, processor settlement, and bank deposit without double counting them."] },
      { heading: "Fees and adjustments can change the net amount", paragraphs: ["Processors may subtract fees, refunds, disputes, reserves, or other adjustments. A customer may also take a discount or deduction. Use settlement or remittance evidence to explain the difference.", "Do not label every short deposit as a processing fee. A consistent historical pattern is a signal, not proof."], bullets: ["Processor fees", "Refunds and chargebacks", "Reserves and settlement adjustments", "Customer deductions or withholding", "Credits and discounts"] },
      { heading: "Partials, overpayments, and timing create real differences", paragraphs: ["A customer may pay part of an invoice, pay in installments, or send more than the current balance. Preserve the applied, remaining, and unapplied amounts separately.", "Payment, settlement, and posting dates can fall in different periods. Bank holidays and processing delays may create valid timing items near month end."] },
      { heading: "The data itself may be wrong or stale", paragraphs: ["A repeated file can duplicate a payment. An invoice export may not include a recent credit. Currency symbols or decimal separators can be parsed incorrectly. A payment might already be reconciled in another period.", "Validate imports and refresh current balances before changing the ledger. When the source records disagree, the reconciliation should show the conflict rather than manufacture agreement."] },
    ],
    example: { label: "Batch settlement", payment: "$9,700.00 bank deposit", invoices: ["Gross receipts  $10,000.00", "Fees and refunds  $300.00"], outcome: "Settlement report explains net", note: "The underlying customer receipts are matched to invoices separately from the net bank deposit." },
    takeaways: ["A deposit may represent one receipt or a batch.", "Use processor and customer remittance evidence.", "Keep applied and unexplained differences separate.", "Document period timing items.", "Validate duplicates, currency, and current balances."],
    related: ["how-to-reconcile-processing-fees-against-invoices", "what-to-do-when-customer-pays-multiple-invoices-in-one-ach", "how-to-handle-partial-invoice-payments"],
  },
];

export const resourceBySlug = Object.fromEntries(resources.map((resource) => [resource.slug, resource])) as Record<string, ResourceArticle>;
export const resourceSlugs = resources.map((resource) => resource.slug);
