import type { Metadata } from "next";
import Link from "next/link";
import { ArrowRight, Check, Minus } from "lucide-react";
import { PlanChooser } from "@/components/marketing/plan-chooser";
import { MarketingFrame } from "@/components/marketing/marketing-frame";
import { canonicalMetadata } from "@/content/seo/seo-components";
import { buttonVariants } from "@/components/ui/button";
import { plans } from "@/lib/config";
import { cn } from "@/lib/utils";

export const metadata: Metadata = canonicalMetadata("Pricing: Free to $99/Month", "Start with 50 payments per month free. Compare $19 Solo, $49 Business and $99 Bookkeeper plans for more payments, client workspaces and custom rules.", "/pricing");

const comparisons = [
  ["Payments per month", "50", "500", "2,500", "10,000"],
  ["Active workspaces", "1", "1", "3", "20"],
  ["Portfolio status dashboard", false, false, true, true],
  ["CSV and XLSX import", true, true, true, true],
  ["Exception review", true, true, true, true],
  ["CSV and XLSX export", true, true, true, true],
  ["Reconciliation history", true, true, true, true],
  ["Custom matching rules", false, false, true, true],
  ["Colleague invitations", false, false, true, true],
  ["Priority support", false, false, true, true],
] as const;

export default function PricingPage() {
  return <MarketingFrame>
    <header className="border-b bg-surface py-16 text-center sm:py-20"><div className="page-shell"><p className="eyebrow">Pricing</p><h1 className="mx-auto mt-5 max-w-4xl text-balance text-4xl font-semibold tracking-[-0.05em] sm:text-6xl">Price the reconciliation volume, not the messiness.</h1><p className="mx-auto mt-5 max-w-2xl text-lg leading-8 text-muted-strong">Reconcile 50 payments every month for free, with imports, matching, review, and exports included. Upgrade for higher volume, more client workspaces, colleague access, or custom matching rules.</p></div></header>
    <PlanChooser />
    <section className="py-14 sm:py-20"><div className="page-shell"><div className="grid gap-px border bg-border md:grid-cols-2 lg:grid-cols-4">{plans.map((plan) => <article className={cn("relative bg-surface p-6", "highlighted" in plan && plan.highlighted ? "ring-2 ring-inset ring-brand" : "")} key={plan.key}>{"highlighted" in plan && plan.highlighted ? <span className="absolute right-4 top-4 bg-brand-soft px-2 py-1 text-xs font-bold text-brand">For teams</span> : null}<h2 className="text-lg font-semibold">{plan.name}</h2><p className="numeric mt-6 text-4xl font-semibold tracking-[-0.04em]">${plan.price}<span className="ml-1 text-sm font-normal text-muted">/month</span></p><p className="mt-4 min-h-18 text-sm leading-6 text-muted">{plan.description}</p><p className="mt-5 border-t pt-4 text-sm font-semibold">{plan.paymentLimit.toLocaleString()} payments per month</p><ul className="mt-5 space-y-3">{plan.features.map((feature) => <li className="flex gap-2 text-sm text-muted-strong" key={feature}><Check className="mt-0.5 size-4 shrink-0 text-success" />{feature}</li>)}</ul><Link className={cn(buttonVariants({ variant: plan.key === "free" ? "secondary" : "primary" }), "mt-7 w-full")} href={`/auth/sign-up?plan=${plan.key}`}>{plan.key === "free" ? "Start free" : `Choose ${plan.name}`}</Link></article>)}</div><p className="mt-4 text-center text-sm text-muted">Prices in USD. No card for Free. Choosing a paid plan does not charge you until checkout. Paid plans renew monthly until canceled. Taxes may apply.</p></div></section>
    <section className="border-y bg-surface py-14 sm:py-20"><div className="page-shell"><div><p className="eyebrow">Plan details</p><h2 className="mt-4 text-3xl font-semibold tracking-[-0.04em]">Compare what is included.</h2></div><div className="mt-8 overflow-x-auto border" tabIndex={0} aria-label="Scrollable plan comparison"><table className="w-full min-w-[760px] text-left text-sm"><thead className="border-b bg-surface-muted"><tr><th className="p-4">Capability</th>{plans.map((plan) => <th className="p-4 text-center" key={plan.key}>{plan.name}</th>)}</tr></thead><tbody className="divide-y">{comparisons.map(([label, ...values]) => <tr key={label}><th className="p-4 font-medium">{label}</th>{values.map((value, index) => <td className="p-4 text-center text-muted-strong" key={`${label}-${plans[index].key}`}>{typeof value === "boolean" ? value ? <Check className="mx-auto size-4 text-success" aria-label="Included" /> : <Minus className="mx-auto size-4 text-muted" aria-label="Not included" /> : value}</td>)}</tr>)}</tbody></table></div></div></section>
    <section className="py-14 sm:py-20"><div className="page-shell grid gap-10 lg:grid-cols-[0.75fr_1.25fr]"><div><p className="eyebrow">Billing questions</p><h2 className="mt-4 text-3xl font-semibold tracking-[-0.04em]">Clear before checkout.</h2></div><div className="divide-y border-y">{[["What counts toward my monthly limit?", "Payment processing capacity is shared across your organization\u0027s workspaces. Invoice rows do not count as payments, and importing recognized duplicates does not create new payment usage. The app checks capacity before a new reconciliation run."], ["Can I start free and upgrade later?", "Yes. Create your workspace and try a real reconciliation first. Upgrade from billing settings when you need more capacity or paid features; keep the same workspace and records."], ["Can I cancel online?", "Yes. A paid subscription can be canceled through billing settings. Access continues through the paid period unless applicable law requires otherwise."], ["Will a card be charged for the free plan?", "No. The free plan does not require a payment card."], ["What happens at the payment limit?", "The product checks the active plan before saving a new reconciliation. It does not create an undisclosed overage charge."], ["Are accounting integrations included?", "CSV and XLSX imports work now. Connection availability is shown inside the product and is never implied before the provider is actually configured."], ["Do you offer onboarding?", "Email support is included. Bookkeeper and Business customers receive priority help with an initial source mapping."]].map(([question, answer]) => <details className="group py-5" key={question}><summary className="flex cursor-pointer list-none justify-between gap-4 font-semibold">{question}<span className="text-xl font-light text-muted group-open:rotate-45">+</span></summary><p className="mt-3 max-w-2xl text-sm leading-6 text-muted">{answer}</p></details>)}</div></div></section>
    <section className="border-t bg-[#15372a] py-14 text-white"><div className="page-shell flex flex-col gap-7 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-xs font-bold uppercase tracking-[0.12em] text-[#9cdfbd]">Start with evidence</p><h2 className="mt-3 text-3xl font-semibold tracking-[-0.04em]">Put one real reconciliation through the workflow.</h2></div><Link className="inline-flex min-h-12 shrink-0 items-center justify-center gap-2 border border-white bg-white px-5 font-semibold text-[#15372a]" href="/auth/sign-up">Start free <ArrowRight className="size-4" /></Link></div></section>
  </MarketingFrame>;
}
