import type { Metadata } from "next";
import Link from "next/link";
import { ArrowRight, Check, FileSearch, ListChecks, Network, ScanLine, ShieldCheck, TableProperties } from "lucide-react";
import { MarketingFrame } from "@/components/marketing/marketing-frame";
import { canonicalMetadata } from "@/content/seo/seo-components";
import { buttonVariants } from "@/components/ui/button";
import { cn } from "@/lib/utils";

export const metadata: Metadata = canonicalMetadata("Product", "See how InvoiceReconcile imports invoices and payments, proposes explainable matches, routes exceptions, and exports a reviewable reconciliation record.", "/product");

const stages = [
  { icon: TableProperties, number: "01", title: "Map the source once", copy: "Preview CSV or XLSX rows, inspect rejected values, and confirm detected invoice and payment columns before anything is accepted." },
  { icon: ScanLine, number: "02", title: "Run explainable rules", copy: "Evaluate amount, reference, normalized payer, currency, date window, partial balances, fees, and bounded combinations without hiding the source record." },
  { icon: ListChecks, number: "03", title: "Work the exception queue", copy: "Approve a suggestion, add several invoices, split an application, record a fee, reject the candidate, or leave the payment unmatched." },
  { icon: FileSearch, number: "04", title: "Keep the evidence", copy: "Preserve source rows, match reasons, confidence, prior state, decisions, notes, timestamps, and the user responsible for each change." },
];

export default function ProductPage() {
  return <MarketingFrame>
    <section className="border-b py-16 sm:py-24"><div className="page-shell grid gap-12 lg:grid-cols-[0.92fr_1.08fr] lg:items-center"><div><p className="eyebrow">Product</p><h1 className="mt-5 max-w-3xl text-balance text-4xl font-semibold tracking-[-0.05em] sm:text-6xl">One controlled path from bank deposit to confirmed invoice application.</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-muted-strong">InvoiceReconcile separates reliable matches from uncertain ones, shows why each result exists, and gives the final decision to the person responsible for the books.</p><div className="mt-8 flex flex-wrap gap-3"><Link className={buttonVariants({ size: "lg" })} href="/auth/sign-up">Reconcile a file <ArrowRight className="size-4" /></Link><Link className={buttonVariants({ variant: "secondary", size: "lg" })} href="/app/demo">Open sample workspace</Link></div></div><ProductEvidence /></div></section>
    <section className="border-b bg-surface py-16 sm:py-24"><div className="page-shell"><div className="max-w-2xl"><p className="eyebrow">Workflow</p><h2 className="mt-4 text-3xl font-semibold tracking-[-0.04em] sm:text-4xl">Designed around review, not blind automation.</h2></div><div className="mt-10 grid gap-px border bg-border lg:grid-cols-4">{stages.map((stage) => <article className="bg-surface p-6" key={stage.number}><div className="flex items-center justify-between"><stage.icon className="size-5 text-brand" /><span className="font-mono text-xs font-bold text-muted">{stage.number}</span></div><h3 className="mt-12 text-lg font-semibold">{stage.title}</h3><p className="mt-3 text-sm leading-6 text-muted">{stage.copy}</p></article>)}</div></div></section>
    <section className="py-16 sm:py-24"><div className="page-shell grid gap-10 lg:grid-cols-2"><div><p className="eyebrow">Matching coverage</p><h2 className="mt-4 text-3xl font-semibold tracking-[-0.04em]">The exceptions that break a lookup formula.</h2><p className="mt-4 max-w-xl text-base leading-7 text-muted-strong">The engine narrows candidates first, tests only responsible combinations, and labels ambiguity instead of turning a near match into certainty.</p></div><ul className="grid gap-px border bg-border sm:grid-cols-2">{["Exact amount and reference", "Normalized payer identity", "One payment across invoices", "Several payments to one invoice", "Partial and overpayments", "Fees and deductions", "Duplicate source rows", "Ambiguous candidates", "Date-window mismatches", "Currency conflicts"].map((item) => <li className="flex gap-3 bg-background p-4 text-sm font-medium" key={item}><Check className="size-4 shrink-0 text-success" />{item}</li>)}</ul></div></section>
    <section className="border-y bg-[#15372a] py-16 text-white sm:py-20"><div className="page-shell grid gap-10 lg:grid-cols-3"><div><Network className="size-6 text-[#91d8b7]" /><h2 className="mt-6 text-xl font-semibold">Workspace isolation by design</h2><p className="mt-3 text-sm leading-6 text-[#c9dbd2]">Keep memberships, imports, normalized financial records, reconciliation decisions, and audit history isolated by organization and workspace.</p></div><div><ShieldCheck className="size-6 text-[#91d8b7]" /><h2 className="mt-6 text-xl font-semibold">Financial data stays out of growth analytics</h2><p className="mt-3 text-sm leading-6 text-[#c9dbd2]">Admin reporting uses counts, plan status, operational health, and privacy-safe events rather than customer invoice values.</p></div><div><FileSearch className="size-6 text-[#91d8b7]" /><h2 className="mt-6 text-xl font-semibold">Exports remain reviewable</h2><p className="mt-3 text-sm leading-6 text-[#c9dbd2]">Download confirmed matches, unmatched payments, discrepancies, and the current decision record without implying an accounting write-back.</p></div></div></section>
    <section className="py-16 sm:py-20"><div className="page-shell flex flex-col gap-6 border-y py-10 sm:flex-row sm:items-center sm:justify-between"><div><p className="eyebrow">See the working product</p><h2 className="mt-3 text-2xl font-semibold tracking-[-0.03em]">Review a combined payment and a fee discrepancy now.</h2></div><Link className={cn(buttonVariants({ size: "lg" }), "shrink-0")} href="/app/demo">Open sample data <ArrowRight className="size-4" /></Link></div></section>
  </MarketingFrame>;
}

function ProductEvidence() {
  return <div className="border bg-surface shadow-panel"><div className="flex items-center justify-between border-b p-4"><span className="text-sm font-semibold">Match evidence</span><span className="border border-warning/20 bg-warning-soft px-2 py-1 text-xs font-bold text-warning">Review</span></div><div className="p-5"><div className="flex justify-between gap-4"><div><p className="text-xs text-muted">Bluebird Studio deposit</p><p className="numeric mt-1 text-2xl font-semibold">$4,850.00</p></div><div className="text-right"><p className="text-xs text-muted">Invoice INV-10516</p><p className="numeric mt-1 text-2xl font-semibold">$5,000.00</p></div></div><div className="mt-6 grid gap-px border bg-border sm:grid-cols-3">{[["Amount", "-$150.00"], ["Payer", "Name agrees"], ["Timing", "Within 4 days"]].map(([label, value]) => <div className="bg-background p-3" key={label}><p className="text-xs text-muted">{label}</p><p className="mt-1 text-sm font-semibold">{value}</p></div>)}</div><div className="mt-5 border-l-4 border-warning bg-warning-soft p-4"><p className="font-semibold text-warning">Reason has not been assumed</p><p className="mt-1 text-sm leading-6 text-muted-strong">Record a fee, choose another invoice, or leave the payment unmatched.</p></div></div></div>;
}
